[package]
name = "client_leo"
version = "0.1.0"
authors = ["Krahos <krahos@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2"